[project]
name = "bdmm-flow-supplementary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.9.4",
    "pandas>=2.3.3",
    "pip>=25.2",
    "seaborn>=0.13.2",
]
